// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import {PasswordType} from "./PasswordType";

export interface PasswordModel {
    id: number,
    username: string,
    password: string,
    website: string,
    website_url?: string,
    website_icon_url?: string,
    password_type: PasswordType,
}